/**
 * 主进程中能处理的事件名称map
 */

module.exports = {
  SET_FULL_SCREEN: 'SET_FULL_SCREEN',
  QUIT_FULL_SCREEN: 'QUIT_FULL_SCREEN',
  IS_FULL_SCREEN: 'IS_FULL_SCREEN',
  SET_SCREEN_SIZE: 'SET_SCREEN_SIZE',
  SET_RESIZABLE: 'SET_RESIZABLE',
  QUIT_APP: 'QUIT_APP',
  APP_INFO: 'APP_INFO',
  ALERT: 'ALERT',
  TOGGLE_DEVTOOLS: 'TOGGLE_DEVTOOLS'
};
